name: Build, test and push to aws

on:
  push:
    branches:
      - '**'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -  uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore String_Crypter.sln

      - name: Build
        run: dotnet build

      - name: Run tests
        run: dotnet test


  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with: 
          dotnet-version: '8.0'

      - name: Build project  
        run: cd Application; dotnet restore; dotnet publish -o site;

      - name: create zip package
        run: cd Application/site; zip ../../site.zip *;

      - name: Deploy to aws EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_SWEBUS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SWEBUS_SECRET_KEY }}
          application_name: StringCrypter
          environment_name: StringCrypter-env
          version_label: ${{ github.run_id }}
          region: us-east-1
          deployment_package: site.zip